# Generated by Django 5.2.3 on 2025-06-23 12:16

from django.db import migrations # type: ignore


def add_initial_skills(apps, schema_editor):
    Skill = apps.get_model('dris_app', 'Skill')
    initial_skills = ["medic", "translator", "driver", "nurse", "it"]

    for name in initial_skills:
        Skill.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("dris_app", "0002_skill_volunteerinfo"),
    ]

    operations = [
        migrations.RunPython(add_initial_skills)
    ]
