# Generated by Django 5.2.3 on 2025-06-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dris_app", "0003_auto_20250623_2016"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerassignment",
            name="disaster_report",
        ),
        migrations.AddField(
            model_name="volunteerassignment",
            name="aid_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dris_app.aidrequest",
            ),
            preserve_default=False,
        ),
    ]
