# Generated by Django 5.2.3 on 2025-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dris_app", "0004_remove_volunteerassignment_disaster_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerassignment",
            name="citizen_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
